// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: room.proto

package proto_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BgTypes int32

const (
	BgTypes_COLOR BgTypes = 0
	BgTypes_IMAGE BgTypes = 1
)

// Enum value maps for BgTypes.
var (
	BgTypes_name = map[int32]string{
		0: "COLOR",
		1: "IMAGE",
	}
	BgTypes_value = map[string]int32{
		"COLOR": 0,
		"IMAGE": 1,
	}
)

func (x BgTypes) Enum() *BgTypes {
	p := new(BgTypes)
	*p = x
	return p
}

func (x BgTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BgTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_room_proto_enumTypes[0].Descriptor()
}

func (BgTypes) Type() protoreflect.EnumType {
	return &file_room_proto_enumTypes[0]
}

func (x BgTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BgTypes.Descriptor instead.
func (BgTypes) EnumDescriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0}
}

type RoomCreateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Background     string                 `protobuf:"bytes,3,opt,name=background,proto3" json:"background,omitempty"`
	BackgroundType BgTypes                `protobuf:"varint,4,opt,name=background_type,json=backgroundType,proto3,enum=room.BgTypes" json:"background_type,omitempty"`
	UsersIds       []string               `protobuf:"bytes,5,rep,name=users_ids,json=usersIds,proto3" json:"users_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RoomCreateRequest) Reset() {
	*x = RoomCreateRequest{}
	mi := &file_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCreateRequest) ProtoMessage() {}

func (x *RoomCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCreateRequest.ProtoReflect.Descriptor instead.
func (*RoomCreateRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0}
}

func (x *RoomCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoomCreateRequest) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

func (x *RoomCreateRequest) GetBackgroundType() BgTypes {
	if x != nil {
		return x.BackgroundType
	}
	return BgTypes_COLOR
}

func (x *RoomCreateRequest) GetUsersIds() []string {
	if x != nil {
		return x.UsersIds
	}
	return nil
}

type RoomResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Background     string                 `protobuf:"bytes,3,opt,name=background,proto3" json:"background,omitempty"`
	BackgroundType string                 `protobuf:"bytes,4,opt,name=background_type,json=backgroundType,proto3" json:"background_type,omitempty"`
	Users          []*UserResponse        `protobuf:"bytes,5,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RoomResponse) Reset() {
	*x = RoomResponse{}
	mi := &file_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomResponse) ProtoMessage() {}

func (x *RoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomResponse.ProtoReflect.Descriptor instead.
func (*RoomResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1}
}

func (x *RoomResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoomResponse) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

func (x *RoomResponse) GetBackgroundType() string {
	if x != nil {
		return x.BackgroundType
	}
	return ""
}

func (x *RoomResponse) GetUsers() []*UserResponse {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_room_proto protoreflect.FileDescriptor

const file_room_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"room.proto\x12\x04room\x1a\n" +
	"user.proto\"\xbe\x01\n" +
	"\x11RoomCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"background\x18\x03 \x01(\tR\n" +
	"background\x126\n" +
	"\x0fbackground_type\x18\x04 \x01(\x0e2\r.room.BgTypesR\x0ebackgroundType\x12\x1b\n" +
	"\tusers_ids\x18\x05 \x03(\tR\busersIds\"\xb7\x01\n" +
	"\fRoomResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"background\x18\x03 \x01(\tR\n" +
	"background\x12'\n" +
	"\x0fbackground_type\x18\x04 \x01(\tR\x0ebackgroundType\x12(\n" +
	"\x05users\x18\x05 \x03(\v2\x12.user.UserResponseR\x05users*\x1f\n" +
	"\aBgTypes\x12\t\n" +
	"\x05COLOR\x10\x00\x12\t\n" +
	"\x05IMAGE\x10\x01B(Z&github.com/fajarilf/grpc-chat/proto-gob\x06proto3"

var (
	file_room_proto_rawDescOnce sync.Once
	file_room_proto_rawDescData []byte
)

func file_room_proto_rawDescGZIP() []byte {
	file_room_proto_rawDescOnce.Do(func() {
		file_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_proto_rawDesc), len(file_room_proto_rawDesc)))
	})
	return file_room_proto_rawDescData
}

var file_room_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_room_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_room_proto_goTypes = []any{
	(BgTypes)(0),              // 0: room.BgTypes
	(*RoomCreateRequest)(nil), // 1: room.RoomCreateRequest
	(*RoomResponse)(nil),      // 2: room.RoomResponse
	(*UserResponse)(nil),      // 3: user.UserResponse
}
var file_room_proto_depIdxs = []int32{
	0, // 0: room.RoomCreateRequest.background_type:type_name -> room.BgTypes
	3, // 1: room.RoomResponse.users:type_name -> user.UserResponse
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_room_proto_init() }
func file_room_proto_init() {
	if File_room_proto != nil {
		return
	}
	file_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_proto_rawDesc), len(file_room_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_room_proto_goTypes,
		DependencyIndexes: file_room_proto_depIdxs,
		EnumInfos:         file_room_proto_enumTypes,
		MessageInfos:      file_room_proto_msgTypes,
	}.Build()
	File_room_proto = out.File
	file_room_proto_goTypes = nil
	file_room_proto_depIdxs = nil
}
