// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: room.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { UserResponse } from "./user";

export const protobufPackage = "room";

export enum BgTypes {
  COLOR = 0,
  IMAGE = 1,
  UNRECOGNIZED = -1,
}

export function bgTypesFromJSON(object: any): BgTypes {
  switch (object) {
    case 0:
    case "COLOR":
      return BgTypes.COLOR;
    case 1:
    case "IMAGE":
      return BgTypes.IMAGE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return BgTypes.UNRECOGNIZED;
  }
}

export function bgTypesToJSON(object: BgTypes): string {
  switch (object) {
    case BgTypes.COLOR:
      return "COLOR";
    case BgTypes.IMAGE:
      return "IMAGE";
    case BgTypes.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface RoomCreateRequest {
  name: string;
  description: string;
  background: string;
  backgroundType: BgTypes;
  usersIds: string[];
}

export interface RoomResponse {
  name: string;
  description: string;
  background: string;
  backgroundType: string;
  users: UserResponse[];
}

function createBaseRoomCreateRequest(): RoomCreateRequest {
  return { name: "", description: "", background: "", backgroundType: 0, usersIds: [] };
}

export const RoomCreateRequest: MessageFns<RoomCreateRequest> = {
  encode(message: RoomCreateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(18).string(message.description);
    }
    if (message.background !== "") {
      writer.uint32(26).string(message.background);
    }
    if (message.backgroundType !== 0) {
      writer.uint32(32).int32(message.backgroundType);
    }
    for (const v of message.usersIds) {
      writer.uint32(42).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomCreateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomCreateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.background = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.backgroundType = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.usersIds.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RoomCreateRequest {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      background: isSet(object.background) ? globalThis.String(object.background) : "",
      backgroundType: isSet(object.backgroundType)
        ? bgTypesFromJSON(object.backgroundType)
        : isSet(object.background_type)
        ? bgTypesFromJSON(object.background_type)
        : 0,
      usersIds: globalThis.Array.isArray(object?.usersIds)
        ? object.usersIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.users_ids)
        ? object.users_ids.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: RoomCreateRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.background !== "") {
      obj.background = message.background;
    }
    if (message.backgroundType !== 0) {
      obj.backgroundType = bgTypesToJSON(message.backgroundType);
    }
    if (message.usersIds?.length) {
      obj.usersIds = message.usersIds;
    }
    return obj;
  },

  create(base?: DeepPartial<RoomCreateRequest>): RoomCreateRequest {
    return RoomCreateRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RoomCreateRequest>): RoomCreateRequest {
    const message = createBaseRoomCreateRequest();
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.background = object.background ?? "";
    message.backgroundType = object.backgroundType ?? 0;
    message.usersIds = object.usersIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseRoomResponse(): RoomResponse {
  return { name: "", description: "", background: "", backgroundType: "", users: [] };
}

export const RoomResponse: MessageFns<RoomResponse> = {
  encode(message: RoomResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(18).string(message.description);
    }
    if (message.background !== "") {
      writer.uint32(26).string(message.background);
    }
    if (message.backgroundType !== "") {
      writer.uint32(34).string(message.backgroundType);
    }
    for (const v of message.users) {
      UserResponse.encode(v!, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.background = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.backgroundType = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.users.push(UserResponse.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RoomResponse {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      background: isSet(object.background) ? globalThis.String(object.background) : "",
      backgroundType: isSet(object.backgroundType)
        ? globalThis.String(object.backgroundType)
        : isSet(object.background_type)
        ? globalThis.String(object.background_type)
        : "",
      users: globalThis.Array.isArray(object?.users) ? object.users.map((e: any) => UserResponse.fromJSON(e)) : [],
    };
  },

  toJSON(message: RoomResponse): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.background !== "") {
      obj.background = message.background;
    }
    if (message.backgroundType !== "") {
      obj.backgroundType = message.backgroundType;
    }
    if (message.users?.length) {
      obj.users = message.users.map((e) => UserResponse.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<RoomResponse>): RoomResponse {
    return RoomResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RoomResponse>): RoomResponse {
    const message = createBaseRoomResponse();
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.background = object.background ?? "";
    message.backgroundType = object.backgroundType ?? "";
    message.users = object.users?.map((e) => UserResponse.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
