// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: room.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Empty } from "./google/protobuf/empty";
import { UserResponse } from "./type";

export const protobufPackage = "room";

export enum BgTypes {
  COLOR = 0,
  IMAGE = 1,
  UNRECOGNIZED = -1,
}

export function bgTypesFromJSON(object: any): BgTypes {
  switch (object) {
    case 0:
    case "COLOR":
      return BgTypes.COLOR;
    case 1:
    case "IMAGE":
      return BgTypes.IMAGE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return BgTypes.UNRECOGNIZED;
  }
}

export function bgTypesToJSON(object: BgTypes): string {
  switch (object) {
    case BgTypes.COLOR:
      return "COLOR";
    case BgTypes.IMAGE:
      return "IMAGE";
    case BgTypes.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface RoomCreateRequest {
  name: string;
  description: string;
  background: string;
  backgroundType: BgTypes;
  userIds: number[];
}

export interface RoomListRequest {
  forward: boolean;
  cursor: number;
  size: number;
}

export interface RoomId {
  id: number;
}

export interface RoomResponseWithUser {
  id: number;
  name: string;
  description: string;
  background: string;
  backgroundType: string;
  users: UserResponse[];
}

export interface RoomListResponse {
  rooms: RoomResponseWithUser[];
  nextCursor: number;
  prevCursor: number;
  hasMore: boolean;
}

function createBaseRoomCreateRequest(): RoomCreateRequest {
  return { name: "", description: "", background: "", backgroundType: 0, userIds: [] };
}

export const RoomCreateRequest: MessageFns<RoomCreateRequest> = {
  encode(message: RoomCreateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(18).string(message.description);
    }
    if (message.background !== "") {
      writer.uint32(26).string(message.background);
    }
    if (message.backgroundType !== 0) {
      writer.uint32(32).int32(message.backgroundType);
    }
    writer.uint32(42).fork();
    for (const v of message.userIds) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomCreateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomCreateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.background = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.backgroundType = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag === 40) {
            message.userIds.push(reader.int32());

            continue;
          }

          if (tag === 42) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.userIds.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RoomCreateRequest {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      background: isSet(object.background) ? globalThis.String(object.background) : "",
      backgroundType: isSet(object.backgroundType)
        ? bgTypesFromJSON(object.backgroundType)
        : isSet(object.background_type)
        ? bgTypesFromJSON(object.background_type)
        : 0,
      userIds: globalThis.Array.isArray(object?.userIds)
        ? object.userIds.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.user_ids)
        ? object.user_ids.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: RoomCreateRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.background !== "") {
      obj.background = message.background;
    }
    if (message.backgroundType !== 0) {
      obj.backgroundType = bgTypesToJSON(message.backgroundType);
    }
    if (message.userIds?.length) {
      obj.userIds = message.userIds.map((e) => Math.round(e));
    }
    return obj;
  },

  create(base?: DeepPartial<RoomCreateRequest>): RoomCreateRequest {
    return RoomCreateRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RoomCreateRequest>): RoomCreateRequest {
    const message = createBaseRoomCreateRequest();
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.background = object.background ?? "";
    message.backgroundType = object.backgroundType ?? 0;
    message.userIds = object.userIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseRoomListRequest(): RoomListRequest {
  return { forward: false, cursor: 0, size: 0 };
}

export const RoomListRequest: MessageFns<RoomListRequest> = {
  encode(message: RoomListRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.forward !== false) {
      writer.uint32(8).bool(message.forward);
    }
    if (message.cursor !== 0) {
      writer.uint32(16).int32(message.cursor);
    }
    if (message.size !== 0) {
      writer.uint32(24).int32(message.size);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomListRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomListRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.forward = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.cursor = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.size = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RoomListRequest {
    return {
      forward: isSet(object.forward) ? globalThis.Boolean(object.forward) : false,
      cursor: isSet(object.cursor) ? globalThis.Number(object.cursor) : 0,
      size: isSet(object.size) ? globalThis.Number(object.size) : 0,
    };
  },

  toJSON(message: RoomListRequest): unknown {
    const obj: any = {};
    if (message.forward !== false) {
      obj.forward = message.forward;
    }
    if (message.cursor !== 0) {
      obj.cursor = Math.round(message.cursor);
    }
    if (message.size !== 0) {
      obj.size = Math.round(message.size);
    }
    return obj;
  },

  create(base?: DeepPartial<RoomListRequest>): RoomListRequest {
    return RoomListRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RoomListRequest>): RoomListRequest {
    const message = createBaseRoomListRequest();
    message.forward = object.forward ?? false;
    message.cursor = object.cursor ?? 0;
    message.size = object.size ?? 0;
    return message;
  },
};

function createBaseRoomId(): RoomId {
  return { id: 0 };
}

export const RoomId: MessageFns<RoomId> = {
  encode(message: RoomId, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomId {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomId();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RoomId {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: RoomId): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create(base?: DeepPartial<RoomId>): RoomId {
    return RoomId.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RoomId>): RoomId {
    const message = createBaseRoomId();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseRoomResponseWithUser(): RoomResponseWithUser {
  return { id: 0, name: "", description: "", background: "", backgroundType: "", users: [] };
}

export const RoomResponseWithUser: MessageFns<RoomResponseWithUser> = {
  encode(message: RoomResponseWithUser, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    if (message.background !== "") {
      writer.uint32(34).string(message.background);
    }
    if (message.backgroundType !== "") {
      writer.uint32(42).string(message.backgroundType);
    }
    for (const v of message.users) {
      UserResponse.encode(v!, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomResponseWithUser {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomResponseWithUser();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.background = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.backgroundType = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.users.push(UserResponse.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RoomResponseWithUser {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      background: isSet(object.background) ? globalThis.String(object.background) : "",
      backgroundType: isSet(object.backgroundType)
        ? globalThis.String(object.backgroundType)
        : isSet(object.background_type)
        ? globalThis.String(object.background_type)
        : "",
      users: globalThis.Array.isArray(object?.users) ? object.users.map((e: any) => UserResponse.fromJSON(e)) : [],
    };
  },

  toJSON(message: RoomResponseWithUser): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.background !== "") {
      obj.background = message.background;
    }
    if (message.backgroundType !== "") {
      obj.backgroundType = message.backgroundType;
    }
    if (message.users?.length) {
      obj.users = message.users.map((e) => UserResponse.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<RoomResponseWithUser>): RoomResponseWithUser {
    return RoomResponseWithUser.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RoomResponseWithUser>): RoomResponseWithUser {
    const message = createBaseRoomResponseWithUser();
    message.id = object.id ?? 0;
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.background = object.background ?? "";
    message.backgroundType = object.backgroundType ?? "";
    message.users = object.users?.map((e) => UserResponse.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRoomListResponse(): RoomListResponse {
  return { rooms: [], nextCursor: 0, prevCursor: 0, hasMore: false };
}

export const RoomListResponse: MessageFns<RoomListResponse> = {
  encode(message: RoomListResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.rooms) {
      RoomResponseWithUser.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.nextCursor !== 0) {
      writer.uint32(16).int32(message.nextCursor);
    }
    if (message.prevCursor !== 0) {
      writer.uint32(24).int32(message.prevCursor);
    }
    if (message.hasMore !== false) {
      writer.uint32(32).bool(message.hasMore);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomListResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomListResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.rooms.push(RoomResponseWithUser.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.nextCursor = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.prevCursor = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.hasMore = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RoomListResponse {
    return {
      rooms: globalThis.Array.isArray(object?.rooms)
        ? object.rooms.map((e: any) => RoomResponseWithUser.fromJSON(e))
        : [],
      nextCursor: isSet(object.nextCursor)
        ? globalThis.Number(object.nextCursor)
        : isSet(object.next_cursor)
        ? globalThis.Number(object.next_cursor)
        : 0,
      prevCursor: isSet(object.prevCursor)
        ? globalThis.Number(object.prevCursor)
        : isSet(object.prev_cursor)
        ? globalThis.Number(object.prev_cursor)
        : 0,
      hasMore: isSet(object.hasMore)
        ? globalThis.Boolean(object.hasMore)
        : isSet(object.has_more)
        ? globalThis.Boolean(object.has_more)
        : false,
    };
  },

  toJSON(message: RoomListResponse): unknown {
    const obj: any = {};
    if (message.rooms?.length) {
      obj.rooms = message.rooms.map((e) => RoomResponseWithUser.toJSON(e));
    }
    if (message.nextCursor !== 0) {
      obj.nextCursor = Math.round(message.nextCursor);
    }
    if (message.prevCursor !== 0) {
      obj.prevCursor = Math.round(message.prevCursor);
    }
    if (message.hasMore !== false) {
      obj.hasMore = message.hasMore;
    }
    return obj;
  },

  create(base?: DeepPartial<RoomListResponse>): RoomListResponse {
    return RoomListResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RoomListResponse>): RoomListResponse {
    const message = createBaseRoomListResponse();
    message.rooms = object.rooms?.map((e) => RoomResponseWithUser.fromPartial(e)) || [];
    message.nextCursor = object.nextCursor ?? 0;
    message.prevCursor = object.prevCursor ?? 0;
    message.hasMore = object.hasMore ?? false;
    return message;
  },
};

export type RoomServiceService = typeof RoomServiceService;
export const RoomServiceService = {
  createRoom: {
    path: "/room.RoomService/CreateRoom" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: RoomCreateRequest): Buffer => Buffer.from(RoomCreateRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RoomCreateRequest => RoomCreateRequest.decode(value),
    responseSerialize: (value: RoomResponseWithUser): Buffer =>
      Buffer.from(RoomResponseWithUser.encode(value).finish()),
    responseDeserialize: (value: Buffer): RoomResponseWithUser => RoomResponseWithUser.decode(value),
  },
  getRoomById: {
    path: "/room.RoomService/GetRoomById" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: RoomId): Buffer => Buffer.from(RoomId.encode(value).finish()),
    requestDeserialize: (value: Buffer): RoomId => RoomId.decode(value),
    responseSerialize: (value: RoomResponseWithUser): Buffer =>
      Buffer.from(RoomResponseWithUser.encode(value).finish()),
    responseDeserialize: (value: Buffer): RoomResponseWithUser => RoomResponseWithUser.decode(value),
  },
  getListRoom: {
    path: "/room.RoomService/GetListRoom" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: RoomListRequest): Buffer => Buffer.from(RoomListRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RoomListRequest => RoomListRequest.decode(value),
    responseSerialize: (value: RoomListResponse): Buffer => Buffer.from(RoomListResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): RoomListResponse => RoomListResponse.decode(value),
  },
  deleteRoom: {
    path: "/room.RoomService/DeleteRoom" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: RoomId): Buffer => Buffer.from(RoomId.encode(value).finish()),
    requestDeserialize: (value: Buffer): RoomId => RoomId.decode(value),
    responseSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer): Empty => Empty.decode(value),
  },
} as const;

export interface RoomServiceServer extends UntypedServiceImplementation {
  createRoom: handleUnaryCall<RoomCreateRequest, RoomResponseWithUser>;
  getRoomById: handleUnaryCall<RoomId, RoomResponseWithUser>;
  getListRoom: handleUnaryCall<RoomListRequest, RoomListResponse>;
  deleteRoom: handleUnaryCall<RoomId, Empty>;
}

export interface RoomServiceClient extends Client {
  createRoom(
    request: RoomCreateRequest,
    callback: (error: ServiceError | null, response: RoomResponseWithUser) => void,
  ): ClientUnaryCall;
  createRoom(
    request: RoomCreateRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RoomResponseWithUser) => void,
  ): ClientUnaryCall;
  createRoom(
    request: RoomCreateRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RoomResponseWithUser) => void,
  ): ClientUnaryCall;
  getRoomById(
    request: RoomId,
    callback: (error: ServiceError | null, response: RoomResponseWithUser) => void,
  ): ClientUnaryCall;
  getRoomById(
    request: RoomId,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RoomResponseWithUser) => void,
  ): ClientUnaryCall;
  getRoomById(
    request: RoomId,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RoomResponseWithUser) => void,
  ): ClientUnaryCall;
  getListRoom(
    request: RoomListRequest,
    callback: (error: ServiceError | null, response: RoomListResponse) => void,
  ): ClientUnaryCall;
  getListRoom(
    request: RoomListRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RoomListResponse) => void,
  ): ClientUnaryCall;
  getListRoom(
    request: RoomListRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RoomListResponse) => void,
  ): ClientUnaryCall;
  deleteRoom(request: RoomId, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  deleteRoom(
    request: RoomId,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  deleteRoom(
    request: RoomId,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
}

export const RoomServiceClient = makeGenericClientConstructor(RoomServiceService, "room.RoomService") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): RoomServiceClient;
  service: typeof RoomServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
