// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: user.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { RoomResponse, UserResponse } from "./type";

export const protobufPackage = "user";

export interface UserCreateRequest {
  name: string;
  username: string;
  password: string;
}

export interface UserLoginRequest {
  username: string;
  password: string;
}

export interface UserLoginResponse {
  username: string;
  token: string;
}

export interface UserResponseWithRoom {
  id: number;
  name: string;
  username: string;
  rooms: RoomResponse[];
}

function createBaseUserCreateRequest(): UserCreateRequest {
  return { name: "", username: "", password: "" };
}

export const UserCreateRequest: MessageFns<UserCreateRequest> = {
  encode(message: UserCreateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.username !== "") {
      writer.uint32(18).string(message.username);
    }
    if (message.password !== "") {
      writer.uint32(26).string(message.password);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserCreateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserCreateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.password = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserCreateRequest {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
    };
  },

  toJSON(message: UserCreateRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    return obj;
  },

  create(base?: DeepPartial<UserCreateRequest>): UserCreateRequest {
    return UserCreateRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UserCreateRequest>): UserCreateRequest {
    const message = createBaseUserCreateRequest();
    message.name = object.name ?? "";
    message.username = object.username ?? "";
    message.password = object.password ?? "";
    return message;
  },
};

function createBaseUserLoginRequest(): UserLoginRequest {
  return { username: "", password: "" };
}

export const UserLoginRequest: MessageFns<UserLoginRequest> = {
  encode(message: UserLoginRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserLoginRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserLoginRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserLoginRequest {
    return {
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
    };
  },

  toJSON(message: UserLoginRequest): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    return obj;
  },

  create(base?: DeepPartial<UserLoginRequest>): UserLoginRequest {
    return UserLoginRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UserLoginRequest>): UserLoginRequest {
    const message = createBaseUserLoginRequest();
    message.username = object.username ?? "";
    message.password = object.password ?? "";
    return message;
  },
};

function createBaseUserLoginResponse(): UserLoginResponse {
  return { username: "", token: "" };
}

export const UserLoginResponse: MessageFns<UserLoginResponse> = {
  encode(message: UserLoginResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    if (message.token !== "") {
      writer.uint32(18).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserLoginResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserLoginResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserLoginResponse {
    return {
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      token: isSet(object.token) ? globalThis.String(object.token) : "",
    };
  },

  toJSON(message: UserLoginResponse): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create(base?: DeepPartial<UserLoginResponse>): UserLoginResponse {
    return UserLoginResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UserLoginResponse>): UserLoginResponse {
    const message = createBaseUserLoginResponse();
    message.username = object.username ?? "";
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseUserResponseWithRoom(): UserResponseWithRoom {
  return { id: 0, name: "", username: "", rooms: [] };
}

export const UserResponseWithRoom: MessageFns<UserResponseWithRoom> = {
  encode(message: UserResponseWithRoom, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.username !== "") {
      writer.uint32(26).string(message.username);
    }
    for (const v of message.rooms) {
      RoomResponse.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserResponseWithRoom {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserResponseWithRoom();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.rooms.push(RoomResponse.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserResponseWithRoom {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      rooms: globalThis.Array.isArray(object?.rooms) ? object.rooms.map((e: any) => RoomResponse.fromJSON(e)) : [],
    };
  },

  toJSON(message: UserResponseWithRoom): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.rooms?.length) {
      obj.rooms = message.rooms.map((e) => RoomResponse.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<UserResponseWithRoom>): UserResponseWithRoom {
    return UserResponseWithRoom.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UserResponseWithRoom>): UserResponseWithRoom {
    const message = createBaseUserResponseWithRoom();
    message.id = object.id ?? 0;
    message.name = object.name ?? "";
    message.username = object.username ?? "";
    message.rooms = object.rooms?.map((e) => RoomResponse.fromPartial(e)) || [];
    return message;
  },
};

export type UserServiceService = typeof UserServiceService;
export const UserServiceService = {
  register: {
    path: "/user.UserService/Register" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UserCreateRequest): Buffer => Buffer.from(UserCreateRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UserCreateRequest => UserCreateRequest.decode(value),
    responseSerialize: (value: UserResponse): Buffer => Buffer.from(UserResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UserResponse => UserResponse.decode(value),
  },
  login: {
    path: "/user.UserService/Login" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UserLoginRequest): Buffer => Buffer.from(UserLoginRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UserLoginRequest => UserLoginRequest.decode(value),
    responseSerialize: (value: UserLoginResponse): Buffer => Buffer.from(UserLoginResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UserLoginResponse => UserLoginResponse.decode(value),
  },
} as const;

export interface UserServiceServer extends UntypedServiceImplementation {
  register: handleUnaryCall<UserCreateRequest, UserResponse>;
  login: handleUnaryCall<UserLoginRequest, UserLoginResponse>;
}

export interface UserServiceClient extends Client {
  register(
    request: UserCreateRequest,
    callback: (error: ServiceError | null, response: UserResponse) => void,
  ): ClientUnaryCall;
  register(
    request: UserCreateRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UserResponse) => void,
  ): ClientUnaryCall;
  register(
    request: UserCreateRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UserResponse) => void,
  ): ClientUnaryCall;
  login(
    request: UserLoginRequest,
    callback: (error: ServiceError | null, response: UserLoginResponse) => void,
  ): ClientUnaryCall;
  login(
    request: UserLoginRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UserLoginResponse) => void,
  ): ClientUnaryCall;
  login(
    request: UserLoginRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UserLoginResponse) => void,
  ): ClientUnaryCall;
}

export const UserServiceClient = makeGenericClientConstructor(UserServiceService, "user.UserService") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): UserServiceClient;
  service: typeof UserServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
