syntax = "proto3";

package chat;

option go_package = "github.com/fajarilf/grpc-chat/proto";

message Message {
    string username = 1;
    string content = 2;
    int64 timestamp = 3;
    string room = 4;
}

message MessageResponse {
    bool success = 1;
    string message_id = 2;
}

message JoinRequest {
    string username = 1;
    string room = 2;
}

message HistoryRequest {
    string room = 1;
    int32 limit = 2;
}

message HistoryResponse {
    repeated Message message = 1;
}

service ChatService {
    rpc SendMessage(Message) returns (MessageResponse);
    rpc JoinChat(JoinRequest) returns (stream Message);
    rpc Chat(stream Message) returns (stream Message);
    rpc GetHistory(HistoryRequest) returns (HistoryResponse);
}